blank_issues_enabled: false
contact_links:
  - name: General Question or Help
    url: https://github.com/your-org/your-repo/discussions
    about: Please use GitHub Discussions for general questions or help.
